apiVersion: config.istio.io/v1alpha1
kind: RouteRule
metadata:
  name: helloworld-v1-default
spec:
  destination:
    name: helloworld
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100